"""
Convert CIBD XML format to text format.

This module converts CBECC XML files to the text-based CIBD format.
The text format is what CBECC uses for .cibd22, .cibd25 files.

Format structure:
- Top-level standalone properties: RulesetFilename "value"
- Objects: ObjectType "name"
  - Properties: PropertyName = value
  - String properties: PropertyName = "value"
  - References: RefProperty = "ObjectName"
  - Array references: RefProperty[1] = "ObjectName"
  - Object ends with ".."
"""

import xml.etree.ElementTree as ET
from typing import TextIO, Any, Dict, Set
import re


class CIBDXMLToTextConverter:
    """Convert CBECC XML to text format."""

    def __init__(self):
        self.namespace = ''
        self.written_objects: Set[str] = set()

    def convert_file(self, xml_path: str, output_path: str):
        """
        Convert XML file to text format.

        Args:
            xml_path: Path to input XML file
            output_path: Path for output text file
        """
        tree = ET.parse(xml_path)
        root = tree.getroot()

        with open(output_path, 'w', encoding='utf-8') as f:
            self.convert_element(root, f)

    def convert_element(self, root: ET.Element, output: TextIO):
        """
        Convert XML element tree to text format.

        Args:
            root: Root XML element
            output: Output file handle
        """
        # Detect namespace
        if '}' in root.tag:
            self.namespace = root.tag.split('}')[0] + '}'

        # Store root attributes for property override (e.g., RulesetFilename from root takes precedence)
        self.root_attributes = {k: v for k, v in root.attrib.items() if k != 'xmlns'}

        # Write top-level attributes (e.g., RulesetFilename)
        for attr_name, attr_value in root.attrib.items():
            if attr_name != 'xmlns':
                output.write(f'{attr_name}   "{attr_value}"  \n')

        if root.attrib:
            output.write('\n')

        # Initialize deferred siblings list
        self.deferred_siblings = []

        # Check for RulesetFilename child element and write it first
        for child in root:
            child_tag = child.tag.replace(self.namespace, '') if self.namespace else child.tag
            if child_tag == 'RulesetFilename':
                # Extract filename from 'file' attribute
                ruleset_file = child.attrib.get('file', 'T24_2025.bin')
                # Convert CIBD22 ruleset to CIBD25 ruleset for compatibility
                if ruleset_file == 'T24N_2022.bin':
                    ruleset_file = 'T24_2025.bin'
                output.write(f'RulesetFilename   "{ruleset_file}"  \n\n')
                break

        # Process child elements
        for child in root:
            self._write_object(child, output, indent=0)

        # Write any deferred siblings (e.g., ResProj, ProjVar) at root level
        if self.deferred_siblings:
            for sibling in self.deferred_siblings:
                self._write_object(sibling, output, indent=0)

    def _write_object(self, elem: ET.Element, output: TextIO, indent: int = 0):
        """
        Write an object and its properties.

        Args:
            elem: XML element representing object
            output: Output file handle
            indent: Indentation level
        """
        # Get tag name without namespace
        tag = elem.tag.replace(self.namespace, '') if self.namespace else elem.tag

        # Skip RulesetFilename child element (we wrote it as attribute)
        if tag == 'RulesetFilename':
            return

        # Skip results/report objects (generated by CBECC, not needed for file open)
        if tag in ['EUseSummary', 'DwellUnitRpt', 'ResIAQVentRpt', 'ResSCSysRpt', 'ResDHWSysRpt']:
            return

        # Get object name from 'Name' or 'n' child or text content
        obj_name = None
        properties = []
        child_objects = []

        # Track immediate siblings separately from deferred siblings
        immediate_siblings = []  # Written right after this object

        for child in elem:
            child_tag = child.tag.replace(self.namespace, '') if self.namespace else child.tag

            if child_tag == 'n':
                obj_name = child.text
            elif child_tag == 'Name':
                # Use Name as the object name for all objects
                obj_name = child.text
            elif len(child) > 0:
                # Check if this should be a top-level sibling instead of nested
                if self._is_top_level_sibling(child_tag, tag, child):
                    # Determine if this should be immediate or deferred
                    # Residential zone children are immediate (written right after zone)
                    # Other extractions (HVAC, schedules, etc.) are deferred (written at end)
                    if self._is_immediate_sibling(child_tag, tag):
                        immediate_siblings.append(child)
                    else:
                        # Store for writing at root level later
                        if not hasattr(self, 'deferred_siblings'):
                            self.deferred_siblings = []
                        self.deferred_siblings.append(child)
                else:
                    # Regular nested object
                    child_objects.append(child)
            else:
                # Leaf node - it's a property
                properties.append((child_tag, child.text))

        # If no name found, check if element has text content
        if obj_name is None and elem.text and elem.text.strip():
            obj_name = elem.text.strip()

        # Write object header
        indent_str = '   ' * indent
        if obj_name:
            output.write(f'{indent_str}{tag}   "{obj_name}"  \n')
        else:
            # Some objects don't have names
            output.write(f'{indent_str}{tag}\n')

        # CIBD25 Format: Extract ExcptCond* properties from Proj into separate ProjVar element
        projvar_properties = []
        if tag == 'Proj':
            excpt_cond_props = [p for p in properties if p[0].startswith('ExcptCond')]
            if excpt_cond_props:
                # Create ProjVar element
                projvar_name = f"{obj_name} - ProjVar" if obj_name else "ProjVar"
                projvar_properties = excpt_cond_props
                # Remove from Proj properties
                properties = [p for p in properties if not p[0].startswith('ExcptCond')]

        # Write properties - collect them first to handle terminator correctly
        property_lines = []
        for prop_name, prop_value in properties:
            if prop_value is None:
                continue

            # Skip Name if it was used as object name
            if prop_name == 'Name' and obj_name == prop_value:
                continue

            # Skip properties that are defined as root attributes (they're written at top level)
            if hasattr(self, 'root_attributes') and prop_name in self.root_attributes:
                continue

            # Detect if this is a reference (array or single)
            array_match = re.match(r'(.+)\[(\d+)\]', prop_name)

            if array_match:
                # Array reference: MatRef[1] = "Material Name"
                base_name = array_match.group(1)
                index = array_match.group(2)
                property_lines.append(f'{indent_str}   {base_name}[{index}] = "{prop_value}"')
            else:
                # Transform property value if needed (e.g., IAQFanType conversion)
                prop_value = self._transform_property_value(prop_name, prop_value)

                # Determine property type
                prop_type = self._get_property_type(prop_name, prop_value)

                if prop_type == 'number':
                    # Numeric value (no quotes)
                    property_lines.append(f'{indent_str}   {prop_name} = {prop_value}')
                else:
                    # String, reference, or enum (quoted)
                    property_lines.append(f'{indent_str}   {prop_name} = "{prop_value}"')

        # CIBD25 requirement: ResZn/ResOtherZn MUST have Type property
        # This is required even in the flat structure
        if tag in ['ResZn', 'ResOtherZn']:
            has_type = any('Type =' in line for line in property_lines)
            if not has_type:
                # Insert Type as first property - default to "Conditioned"
                # CBECC rules will determine actual conditioning based on HVAC assignments
                property_lines.insert(0, f'{indent_str}   Type = "Conditioned"')

            # CIBD25 requirement: ResOtherZn should have VentSpcFunc to avoid ruleset inference errors
            # If not set, default to "NA" to prevent CBECC from trying to infer using old CIBD22 enumerations
            has_vent = any('VentSpcFunc =' in line for line in property_lines)
            if not has_vent:
                # Add VentSpcFunc = "NA" after Type
                property_lines.insert(1 if not has_type else 2, f'{indent_str}   VentSpcFunc = "NA"')

        # Write all properties
        for line in property_lines:
            output.write(line + '\n')

        # Write nested objects
        for child_obj in child_objects:
            self._write_object(child_obj, output, indent + 1)

        # Write object terminator
        # If there are no nested objects and we have properties, append .. on last property line
        if not child_objects and property_lines:
            # Go back and append .. to last line
            # This requires seeking - simpler to just use correct format from start
            # For now, keep .. on separate line (matches most of official format)
            output.write(f'{indent_str}   ..\n\n')
        else:
            # Standard terminator
            output.write(f'{indent_str}   ..\n\n')

        # Write immediate siblings right after this object (at root level)
        # These are children that were extracted to top level but need to maintain
        # ordering relative to their parent (e.g., zone walls/DwellUnits after zone)
        if immediate_siblings:
            for sibling in immediate_siblings:
                self._write_object(sibling, output, indent=0)

        # CIBD25 Format: Write ProjVar element after Proj if we extracted ExcptCond properties
        if tag == 'Proj' and projvar_properties:
            output.write(f'ProjVar   "{projvar_name}"  \n')
            for prop_name, prop_value in projvar_properties:
                if prop_value is None:
                    continue
                # All ExcptCond properties are string enumerations
                output.write(f'   {prop_name} = "{prop_value}"\n')
            output.write('   ..\n\n')

    def _transform_property_value(self, prop_name: str, prop_value: str) -> str:
        """
        Transform property values for CIBD25 compatibility.

        Args:
            prop_name: Name of the property
            prop_value: Original value from source

        Returns:
            Transformed value (or original if no transformation needed)
        """
        # No transformations currently needed - property values are preserved as-is
        return prop_value

    def _is_number(self, value: str) -> bool:
        """Check if value is a number (int or float)."""
        if value is None:
            return False
        try:
            float(value)
            return True
        except (ValueError, TypeError):
            return False

    def _is_reference(self, prop_name: str) -> bool:
        """Check if property name indicates a reference."""
        ref_patterns = [
            'Ref', 'Type', 'Schedule', 'System', 'Zone', 'Space',
            'Bldg', 'Story', 'Surface', 'Window', 'Door'
        ]
        return any(pattern in prop_name for pattern in ref_patterns)

    def _is_top_level_sibling(self, child_tag: str, parent_tag: str, child=None) -> bool:
        """
        Check if an element should be written as a top-level sibling instead of nested.

        In CIBD XML, many elements are nested inside Proj for document organization,
        but in CIBD text format they must be top-level siblings (catalog objects).

        Args:
            child_tag: Tag of the child element
            parent_tag: Tag of the parent element
            child: The child XML element (optional, needed for attribute checks)

        Returns:
            True if child should be written as top-level sibling
        """
        # Elements that appear as children of Proj in XML but should be siblings in text
        if parent_tag == 'Proj':
            # Schedule objects (catalog objects)
            if child_tag in ['SchDay', 'SchWeek', 'Sch']:
                return True

            # Project variants (compliance data)
            if child_tag in ['ResProj', 'ProjVar']:
                return True

            # Building object (must be top-level sibling to Proj in CIBD25)
            if child_tag == 'Bldg':
                return True

            # Dwelling unit type definitions
            if child_tag == 'DwellUnitType':
                return True

            # Project-level systems (must be top-level siblings to Proj)
            if child_tag in ['FluidSys', 'PVArray', 'Batt', 'ProjVar']:
                return True

            # Residential HVAC catalog (all systems are top-level library objects)
            if child_tag in [
                'ResHtgSys',           # Heating systems
                'ResClgSys',           # Cooling systems
                'ResHtPumpSys',        # Heat pump systems
                'ResDistSys',          # Distribution systems
                'ResFanSys',           # Fan systems
                'ResIAQFan',           # IAQ fans
                'ResDHWSys',           # DHW systems
                'ResWtrHtr',           # Water heaters
                'ResLpTankHtr',        # Loop tank heaters
                'ResCentralVentSys',   # Central ventilation
            ]:
                return True

            # Residential construction catalog
            if child_tag in [
                'ResConsAssm',         # Construction assemblies
                'ResMat',              # Materials
                'ResWinType',          # Window types
            ]:
                return True

            # HERS/Compliance objects
            if child_tag in [
                'HERSCool',            # HERS cooling
                'HERSHeat',            # HERS heating
                'HERSHtPump',          # HERS heat pump
                'HERSDist',            # HERS distribution
                'HERSFan',             # HERS fan
                'HERSDHWSys',          # HERS DHW
                'HERSOther',           # HERS other
                'SpeclFtr',            # Special features
                # NOTE: ResZnGrp removed - it's a child of Bldg, not Proj
            ]:
                return True

            # Construction library and equipment catalog elements that appear as children
            # of Proj in XML but must be extracted as top-level siblings in CIBD25 text format
            if child_tag in [
                'ConsAssm',            # Construction assemblies
                'Mat',                 # Materials
                'FenCons',             # Fenestration constructions
                'DrCons',              # Door constructions
                'SpcFuncDefaults',     # Space function defaults
                'Lum',                 # Luminaires (lighting fixtures)
                'WtrHtr',              # Water heaters
                'Chiller',             # Chillers
                'Boiler',              # Boilers
                'Pump',                # Pumps
                'ThrmlEngyStor',       # Thermal energy storage
            ]:
                return True

            # Report objects
            if child_tag in [
                'ResDHWSysRpt',        # DHW system reports
                'DwellUnitRpt',        # Dwelling unit reports
                'ResIAQVentRpt',       # IAQ ventilation reports
                'ResSCSysRpt',         # Space conditioning reports
                'EUseSummary',         # End use summary
            ]:
                return True

        # Elements that appear as children of Bldg in XML but should be siblings in text
        if parent_tag == 'Bldg':
            # Story elements must be extracted to top level
            if child_tag == 'Story':
                return True

            # Residential zone groups must be extracted to top level
            if child_tag == 'ResZnGrp':
                return True

            # Commercial thermal zones and zone systems must be extracted to top level
            if child_tag in ['ThrmlZn', 'ZnSys']:
                return True

            # Commercial HVAC systems must be extracted to top level
            if child_tag == 'AirSys':
                return True

            # VRF systems (Variable Refrigerant Flow) must be extracted to top level
            if child_tag == 'VRFSys':
                return True

        # Elements that appear as children of Story in XML but should be siblings in text
        if parent_tag == 'Story':
            # Spaces must be extracted to top level
            if child_tag == 'Spc':
                return True

        # Elements that appear as children of ZnSys in XML but should be siblings in text
        if parent_tag == 'ZnSys':
            # HVAC components nested under ZnSys must be extracted to top level
            if child_tag in ['CoilClg', 'CoilHtg', 'Fan', 'Htg', 'Clg']:
                return True

        # Elements that appear as children of Spc in XML but should be siblings in text
        if parent_tag == 'Spc':
            # Building envelope components and lighting systems nested under Spc must be extracted to top level
            if child_tag in ['ExtWall', 'IntWall', 'UndgrFlr', 'UndgrWall', 'Flr', 'Roof', 'Ceiling', 'IntFlr', 'ExtFlr', 'IntLtgSys']:
                return True

        # Elements that appear as children of ExtWall in XML but should be siblings in text
        if parent_tag == 'ExtWall':
            # Windows and doors (commercial) must be extracted to top level
            if child_tag in ['Win', 'Dr']:
                return True

        # Elements that appear as children of FluidSys in XML but should be siblings in text
        if parent_tag == 'FluidSys':
            # Fluid segments and water heaters must be extracted to top level
            # They reference each other through FluidSegOutRef/FluidSegMakeupRef properties
            if child_tag in ['FluidSeg', 'WtrHtr']:
                return True

        # Elements that appear as children of AirSys in XML but should be siblings in text
        if parent_tag == 'AirSys':
            # Air segments and HVAC components must be extracted to top level
            # Similar to FluidSys structure - components are top-level siblings
            if child_tag in ['AirSeg', 'CoilClg', 'CoilHtg', 'Fan', 'TrmlUnit', 'OACtrl', 'EvapClr']:
                return True

        # Elements that appear as children of AirSeg in XML but should be siblings in text
        if parent_tag == 'AirSeg':
            # HVAC components nested under AirSeg must also be extracted to top level
            # They are top-level siblings in CIBD25 format, not nested under AirSeg
            if child_tag in ['CoilClg', 'CoilHtg', 'Fan', 'OACtrl']:
                return True

        # CRITICAL: In CIBD25 text format, ResZnGrp is an empty container and ALL
        # residential zone elements are top-level siblings (not nested)

        # Elements that appear as children of ResZnGrp in XML but should be siblings in text
        if parent_tag == 'ResZnGrp':
            # All zone types must be extracted to top level in CIBD25
            if child_tag in ['ResZn', 'ResOtherZn', 'ResAttic']:
                return True

        # Elements that appear as children of ResZn in XML but should be siblings in text
        if parent_tag == 'ResZn':
            # ALL children of ResZn must be extracted to top level in CIBD25
            if child_tag in [
                'DwellUnit',           # Dwelling units
                'ResExtWall',          # Exterior walls
                'ResIntWall',          # Interior walls
                'ResSlabFlr',          # Slab floors
                'ResIntFlr',           # Interior floors
                'ResCathedralCeiling', # Cathedral ceilings
                'ResCeilingBelowAttic',# Ceiling below attic
                'ResOpening',          # Openings (doors)
                'ResExtFlr',           # Exterior floors
                'ResAtticRoof',        # Attic roofs
                'IntLtgSys',           # Interior lighting systems
            ]:
                return True

        # Elements that appear as children of ResOtherZn in XML but should be siblings in text
        if parent_tag == 'ResOtherZn':
            # ALL children of ResOtherZn must be extracted to top level in CIBD25
            if child_tag in [
                'ResExtWall',          # Exterior walls
                'ResIntWall',          # Interior walls
                'ResSlabFlr',          # Slab floors
                'ResIntFlr',           # Interior floors
                'ResCathedralCeiling', # Cathedral ceilings
                'ResCeilingBelowAttic',# Ceiling below attic
                'ResOpening',          # Openings (doors)
                'ResExtFlr',           # Exterior floors
                'ResAtticRoof',        # Attic roofs
                'IntLtgSys',           # Interior lighting systems
            ]:
                return True

        # Elements that appear as children of ResExtWall in XML but should be siblings in text
        if parent_tag == 'ResExtWall':
            # Windows and doors must be extracted to top level
            if child_tag in ['ResWin', 'ResDr']:
                return True

        # Elements that appear as children of ResAtticRoof in XML but should be siblings in text
        if parent_tag == 'ResAtticRoof':
            # Skylights must be extracted to top level
            if child_tag == 'ResSkylt':
                return True

        return False

    def _is_immediate_sibling(self, child_tag: str, parent_tag: str) -> bool:
        """
        Determine if extracted child should be written immediately after parent.

        Residential zone children need immediate writing to maintain proper ordering.
        Commercial HVAC children also need immediate writing to maintain hierarchy.
        Other extractions (schedules, etc.) can be deferred to end.
        """
        # CRITICAL: Children of Bldg (ResZnGrp) must be written immediately after Bldg
        # This maintains proper CBECC GUI hierarchy: Bldg → ResZnGrp → ResZn → geometry
        # If deferred, ResProj/schedules get written first, breaking GUI display
        if parent_tag == 'Bldg' and child_tag == 'ResZnGrp':
            return True

        # Children of ResZn/ResOtherZn must be written immediately after the zone
        if parent_tag in ['ResZn', 'ResOtherZn']:
            if child_tag in ['DwellUnit', 'ResExtWall', 'ResIntWall', 'ResSlabFlr',
                            'ResIntFlr', 'ResCathedralCeiling', 'ResCeilingBelowAttic',
                            'ResOpening', 'ResExtFlr', 'ResAtticRoof', 'IntLtgSys']:
                return True

        # Children of ResExtWall must be written immediately
        if parent_tag == 'ResExtWall' and child_tag in ['ResWin', 'ResDr']:
            return True

        # Children of ExtWall (commercial) must be written immediately
        if parent_tag == 'ExtWall' and child_tag in ['Win', 'Dr']:
            return True

        # Children of ResAtticRoof must be written immediately
        if parent_tag == 'ResAtticRoof' and child_tag == 'ResSkylt':
            return True

        # Children of ResZnGrp (ResZn, ResOtherZn) must be written immediately
        if parent_tag == 'ResZnGrp' and child_tag in ['ResZn', 'ResOtherZn', 'ResAttic']:
            return True

        # Children of AirSys must be written immediately after the parent
        if parent_tag == 'AirSys' and child_tag in ['AirSeg', 'TrmlUnit', 'OACtrl']:
            return True

        # Children of AirSeg must be written immediately after the parent
        if parent_tag == 'AirSeg' and child_tag in ['CoilClg', 'CoilHtg', 'Fan']:
            return True

        # Children of FluidSys must be written immediately after the parent
        if parent_tag == 'FluidSys' and child_tag == 'FluidSeg':
            return True

        # All other extractions are deferred
        return False

    def _requires_quotes(self, prop_name: str) -> bool:
        """
        Check if property should always be quoted (even if numeric-looking).

        This handles properties where CBECC schema defines them as STRING or ENUM type
        even though they may contain digits or look numeric.
        """
        # Properties that must be quoted (STRING or ENUM fields in CBECC schema)
        always_quote = [
            # Author/document metadata (STRING fields)
            'DocAuthZipCode',      # Author ZIP - STRING (can have leading zeros)
            'DocAuthAddress',      # Author address
            'DocAuthCity',         # Author city
            'DocAuthState',        # Author state
            'DocAuthCompany',      # Author company

            # Location/weather (STRING fields)
            'StAddress',           # Street address
            'City',                # City name
            'State',               # State abbreviation
            'WeatherStation',      # Weather station name
            'WeatherFileName',     # Weather file name
            'DDWeatherFile',       # Design day weather file
            'AnnualWeatherFile',   # Annual weather file
            'AnnualWeatherFileNoPath',  # Weather file (no path)

            # Date/time strings (STRING fields)
            'RunDateFmt',          # Formatted date
            'RunDateISO',          # ISO date

            # Enum/choice properties (always quoted in CBECC)
            'Status',              # Component status (New, Existing, etc.)
            'DryerFuel',           # Dryer fuel type
            'CookingApplType',     # Cooking appliance type
            'CliZn',               # Climate zone (e.g., "ClimateZone12")
            'Orientation',         # Orientation (Front, Back, Left, Right)
            'GasType',             # Gas type (NaturalGas, Propane)
            'AnalysisType',        # Analysis type
            'SimSpeedOption',      # Simulation speed option

            # Exception conditions (enum fields)
            'ExcptCondNoClgSys',   # "Yes" or "No"
            'ExcptCondRtdCap',     # "Yes" or "No"
            'ExcptCondNarrative',  # "Yes" or "No"

            # Construction properties (STRING/ENUM fields)
            'Type',                # Component type (generic enum)
            'CanAssignTo',         # Construction assignment type
            'MassLayer',           # Mass layer material name
            'MassThickness',       # Mass thickness (e.g., "8 in.", "- none -")

            # HVAC properties (enum fields)
            'FanCtrlMthd',         # Fan control method
            'FuelType',            # Fuel type

            # Residential properties (enum fields)
            'InsulConsQuality',    # Insulation quality ("No", "Yes")
            'UnitClVentOption',    # Unit ventilation option

            # Special format strings
            'SoftwareVersion',     # Version string (e.g., "CBECC 2025.1.0 (1381)")
            'RunTitle',            # Run title
            'ResultsCurrentMessage',  # Results message

            # NOTE: 'ZipCode' is an INTEGER field - should NOT be quoted
        ]
        return prop_name in always_quote

    def _get_property_type(self, prop_name: str, prop_value: str) -> str:
        """
        Determine property type for quoting decisions.

        Args:
            prop_name: Name of the property
            prop_value: Value of the property

        Returns:
            'string', 'number', 'reference', or 'enum'
        """
        # Force-quoted properties (from _requires_quotes)
        if self._requires_quotes(prop_name):
            return 'string'

        # Numeric properties (never quoted) - CHECK BEFORE REFERENCE PATTERNS
        # This is crucial because some numeric properties like BldgEngyModelVersion
        # contain substrings that match reference patterns (e.g., 'Bldg')
        if self._is_number(prop_value):
            return 'number'

        # Reference properties (always quoted)
        if self._is_reference(prop_name):
            return 'reference'

        # Boolean-like keywords (quoted as enums)
        if prop_value and prop_value.lower() in ['true', 'false', 'yes', 'no']:
            return 'enum'

        # Default to string (quoted)
        return 'string'

    def _is_string_value(self, value: str) -> bool:
        """Check if value should be quoted as string."""
        if value is None:
            return False

        # Check if it's a number
        if self._is_number(value):
            return False

        # Check if it's a boolean-like keyword
        if value.lower() in ['true', 'false', 'yes', 'no']:
            return True

        # Everything else is a string
        return True


def convert_xml_to_text(xml_path: str, text_path: str):
    """
    Convenience function to convert XML to text format.

    Args:
        xml_path: Path to input XML file
        text_path: Path for output text file
    """
    converter = CIBDXMLToTextConverter()
    converter.convert_file(xml_path, text_path)


if __name__ == '__main__':
    import sys
    if len(sys.argv) != 3:
        print("Usage: python cibd_xml_to_text.py <input.xml> <output.cibd25>")
        sys.exit(1)

    convert_xml_to_text(sys.argv[1], sys.argv[2])
    print(f"✅ Converted {sys.argv[1]} → {sys.argv[2]}")
