"""
PDF Export for LCCA Reports.

Provides:
- ECON-1 PDF generation
- LCCA summary PDF
- Professional formatting with charts

Requires: reportlab (pip install reportlab)
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, List
from io import BytesIO

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Image
    )
    from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

from .calculators import LccaResults
from .econ1 import Econ1Report


@dataclass
class PdfExportOptions:
    """Options for PDF export."""
    include_cover_page: bool = True
    include_cash_flow_table: bool = True
    company_name: str = ""
    company_logo: str = ""  # Path to logo file
    prepared_by: str = ""
    footer_text: str = "Generated by ECO Tools LCCA Module"


def _check_reportlab():
    """Check if reportlab is available."""
    if not REPORTLAB_AVAILABLE:
        raise ImportError(
            "reportlab is required for PDF export. "
            "Install with: pip install reportlab"
        )


def _create_styles():
    """Create custom paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name='Title_Custom',
        parent=styles['Title'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER
    ))

    styles.add(ParagraphStyle(
        name='Subtitle',
        parent=styles['Normal'],
        fontSize=14,
        spaceAfter=20,
        alignment=TA_CENTER,
        textColor=colors.gray
    ))

    styles.add(ParagraphStyle(
        name='SectionHeader',
        parent=styles['Heading2'],
        fontSize=14,
        spaceBefore=20,
        spaceAfter=10,
        textColor=colors.HexColor('#2E5090')
    ))

    styles.add(ParagraphStyle(
        name='TableHeader',
        parent=styles['Normal'],
        fontSize=10,
        fontName='Helvetica-Bold',
        alignment=TA_CENTER
    ))

    styles.add(ParagraphStyle(
        name='Currency',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_RIGHT
    ))

    return styles


def _format_currency(value: float) -> str:
    """Format value as currency string."""
    if value < 0:
        return f"(${abs(value):,.0f})"
    return f"${value:,.0f}"


def _format_number(value: float, decimals: int = 0) -> str:
    """Format number with commas."""
    if decimals == 0:
        return f"{value:,.0f}"
    return f"{value:,.{decimals}f}"


def _format_percent(value: float) -> str:
    """Format as percentage."""
    return f"{value * 100:.1f}%"


def export_econ1_to_pdf(
    econ1: Econ1Report,
    file_path: str,
    options: Optional[PdfExportOptions] = None
) -> str:
    """
    Export ECON-1 report to PDF.

    Args:
        econ1: Econ1Report object
        file_path: Output file path (.pdf)
        options: Export options

    Returns:
        Path to created file
    """
    _check_reportlab()

    if options is None:
        options = PdfExportOptions()

    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    styles = _create_styles()
    story = []

    # Title
    story.append(Paragraph("ECON-1", styles['Title_Custom']))
    story.append(Paragraph("Energy Cost Analysis Report", styles['Subtitle']))
    story.append(Spacer(1, 20))

    # Project Information
    story.append(Paragraph("Project Information", styles['SectionHeader']))

    project_data = [
        ["Project Name:", econ1.project_name or "N/A"],
        ["Building Type:", econ1.building_type or "N/A"],
        ["Conditioned Area:", f"{econ1.conditioned_area_sf:,.0f} SF"],
        ["Analysis Date:", econ1.analysis_date or "N/A"],
        ["Software:", econ1.software_version or "N/A"],
    ]

    project_table = Table(project_data, colWidths=[2*inch, 4.5*inch])
    project_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(project_table)
    story.append(Spacer(1, 15))

    # Utility Rates
    story.append(Paragraph("Utility Rates", styles['SectionHeader']))

    rates_data = [
        ["Tariff:", econ1.tariff_name or "N/A"],
        ["Electric Rate:", f"${econ1.elec_rate:.4f}/kWh"],
        ["Gas Rate:", f"${econ1.gas_rate:.2f}/therm"],
        ["Demand Rate:", f"${econ1.demand_rate:.2f}/kW-mo"],
    ]

    rates_table = Table(rates_data, colWidths=[2*inch, 4.5*inch])
    rates_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(rates_table)
    story.append(Spacer(1, 15))

    # Proposed Building Energy
    story.append(Paragraph("Proposed Building - Annual Energy", styles['SectionHeader']))

    proposed = econ1.proposed
    energy_data = [
        ["Energy Type", "Quantity", "Units"],
        ["Electricity", _format_number(proposed.elec_kwh_gross), "kWh"],
        ["Natural Gas", _format_number(proposed.gas_therm, 1), "therms"],
        ["Peak Demand", _format_number(proposed.peak_demand_kw, 1), "kW"],
    ]

    if proposed.generation and proposed.generation.pv_generation_kwh > 0:
        energy_data.append([
            "PV Generation",
            _format_number(proposed.generation.pv_generation_kwh),
            "kWh"
        ])

    energy_table = Table(energy_data, colWidths=[2.5*inch, 2*inch, 2*inch])
    energy_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(energy_table)
    story.append(Spacer(1, 15))

    # Proposed Building Costs
    story.append(Paragraph("Proposed Building - Annual Costs", styles['SectionHeader']))

    cost_data = [
        ["Cost Category", "Amount"],
        ["Electricity Cost", _format_currency(proposed.elec_cost_gross)],
        ["Natural Gas Cost", _format_currency(proposed.gas_cost)],
        ["Demand Charges", _format_currency(proposed.demand_cost)],
        ["Gross Total", _format_currency(proposed.gross_cost)],
    ]

    if proposed.pv_savings > 0:
        cost_data.append(["PV Credit", f"({_format_currency(proposed.pv_savings)})"])

    cost_data.append(["NET ANNUAL COST", _format_currency(proposed.net_cost)])

    cost_table = Table(cost_data, colWidths=[3.5*inch, 3*inch])
    cost_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#D9E2F3')),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(cost_table)
    story.append(Spacer(1, 15))

    # Baseline and Comparison if available
    if econ1.baseline:
        story.append(Paragraph("Baseline Building - Annual Costs", styles['SectionHeader']))

        baseline = econ1.baseline
        baseline_data = [
            ["Cost Category", "Amount"],
            ["Electricity Cost", _format_currency(baseline.elec_cost_gross)],
            ["Natural Gas Cost", _format_currency(baseline.gas_cost)],
            ["Demand Charges", _format_currency(baseline.demand_cost)],
            ["NET ANNUAL COST", _format_currency(baseline.net_cost)],
        ]

        baseline_table = Table(baseline_data, colWidths=[3.5*inch, 3*inch])
        baseline_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#D9E2F3')),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(baseline_table)
        story.append(Spacer(1, 15))

        # Cost Comparison
        story.append(Paragraph("Cost Comparison", styles['SectionHeader']))

        comparison_data = [
            ["Metric", "Value"],
            ["Annual Savings", _format_currency(econ1.annual_savings or 0)],
            ["Percent Savings", f"{econ1.percent_savings:.1f}%" if econ1.percent_savings else "N/A"],
        ]

        comparison_table = Table(comparison_data, colWidths=[3.5*inch, 3*inch])
        comparison_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#70AD47')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(comparison_table)

    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph(
        options.footer_text,
        ParagraphStyle(
            name='Footer',
            fontSize=8,
            textColor=colors.gray,
            alignment=TA_CENTER
        )
    ))

    doc.build(story)
    return file_path


def export_lcca_to_pdf(
    results: LccaResults,
    file_path: str,
    project_name: str = "LCCA Analysis",
    options: Optional[PdfExportOptions] = None
) -> str:
    """
    Export LCCA results to PDF.

    Args:
        results: LccaResults from run_lcca()
        file_path: Output file path (.pdf)
        project_name: Project name for header
        options: Export options

    Returns:
        Path to created file
    """
    _check_reportlab()

    if options is None:
        options = PdfExportOptions()

    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    styles = _create_styles()
    story = []

    # Title
    story.append(Paragraph("Life Cycle Cost Analysis", styles['Title_Custom']))
    story.append(Paragraph(project_name, styles['Subtitle']))
    story.append(Spacer(1, 20))

    # Investment Summary
    story.append(Paragraph("Investment Summary", styles['SectionHeader']))

    investment_data = [
        ["Item", "Amount"],
        ["Initial Investment", _format_currency(results.initial_investment)],
        ["Total Incentives (PV)", _format_currency(results.total_incentives)],
        ["Net Investment", _format_currency(results.net_investment)],
    ]

    investment_table = Table(investment_data, colWidths=[3.5*inch, 3*inch])
    investment_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(investment_table)
    story.append(Spacer(1, 15))

    # Annual Costs
    story.append(Paragraph("Annual Costs (Year 1)", styles['SectionHeader']))

    annual_data = [
        ["Item", "Amount"],
        ["Baseline Annual Cost", _format_currency(results.baseline_annual_cost)],
        ["Proposed Annual Cost", _format_currency(results.proposed_annual_cost)],
        ["Annual Savings", _format_currency(results.annual_savings)],
    ]

    annual_table = Table(annual_data, colWidths=[3.5*inch, 3*inch])
    annual_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(annual_table)
    story.append(Spacer(1, 15))

    # Financial Metrics
    story.append(Paragraph("Financial Metrics", styles['SectionHeader']))

    metrics_data = [
        ["Metric", "Value"],
        ["Net Present Value (NPV)", _format_currency(results.npv)],
        ["Internal Rate of Return (IRR)",
         _format_percent(results.irr) if results.irr else "N/A"],
        ["Simple Payback",
         f"{results.simple_payback_years:.1f} years" if results.simple_payback_years else "N/A"],
        ["Discounted Payback",
         f"{results.discounted_payback_years:.1f} years" if results.discounted_payback_years else "N/A"],
        ["Savings-to-Investment Ratio",
         f"{results.sir:.2f}" if results.sir else "N/A"],
    ]

    metrics_table = Table(metrics_data, colWidths=[3.5*inch, 3*inch])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#70AD47')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 15))

    # Lifecycle Costs
    story.append(Paragraph("Lifecycle Costs (Present Value)", styles['SectionHeader']))

    lifecycle_data = [
        ["Item", "Amount"],
        ["Baseline Lifecycle Cost", _format_currency(results.baseline_lifecycle_cost)],
        ["Proposed Lifecycle Cost", _format_currency(results.proposed_lifecycle_cost)],
        ["Lifecycle Savings", _format_currency(results.lifecycle_savings)],
    ]

    lifecycle_table = Table(lifecycle_data, colWidths=[3.5*inch, 3*inch])
    lifecycle_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(lifecycle_table)
    story.append(Spacer(1, 15))

    # Cash Flow Table (if requested)
    if options.include_cash_flow_table and results.cash_flows:
        story.append(PageBreak())
        story.append(Paragraph("Cash Flow Schedule", styles['SectionHeader']))

        cf_data = [["Year", "Cash Flow", "Cumulative", "Category"]]
        for i, cf in enumerate(results.cash_flows[:25]):  # Limit to 25 rows
            cumulative = results.cumulative_cash_flows[i] if i < len(results.cumulative_cash_flows) else 0
            cf_data.append([
                str(cf.year),
                _format_currency(cf.amount),
                _format_currency(cumulative),
                cf.category.title()
            ])

        cf_table = Table(cf_data, colWidths=[1*inch, 2*inch, 2*inch, 1.5*inch])
        cf_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (0, -1), 'CENTER'),
            ('ALIGN', (1, 0), (2, -1), 'RIGHT'),
            ('ALIGN', (3, 0), (3, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F2F2F2')]),
        ]))
        story.append(cf_table)

    # Analysis Parameters
    story.append(Spacer(1, 20))
    story.append(Paragraph("Analysis Parameters", styles['SectionHeader']))

    params_data = [
        ["Parameter", "Value"],
        ["Analysis Period", f"{results.analysis_years} years"],
        ["Real Discount Rate", _format_percent(results.discount_rate)],
    ]

    params_table = Table(params_data, colWidths=[3.5*inch, 3*inch])
    params_table.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(params_table)

    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph(
        options.footer_text,
        ParagraphStyle(
            name='Footer',
            fontSize=8,
            textColor=colors.gray,
            alignment=TA_CENTER
        )
    ))

    doc.build(story)
    return file_path
